In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [3]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [11]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [13]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

In [14]:
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [15]:
dframe1

X         Y         Z
0  0.603620  1.045708 -0.546797
1  0.947378 -0.331644  0.135510
2 -0.449009  0.939663 -0.077299
3 -1.198898  2.134181  1.051128

In [16]:
dframe2

Y         Q         X
0 -1.161798 -0.583932 -0.556500
1  1.022473 -0.806674  2.118057
2 -0.693955 -2.101105 -0.272598

In [17]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.603620  1.045708 -0.546797
1       NaN  0.947378 -0.331644  0.135510
2       NaN -0.449009  0.939663 -0.077299
3       NaN -1.198898  2.134181  1.051128
0 -0.583932 -0.556500 -1.161798       NaN
1 -0.806674  2.118057  1.022473       NaN
2 -2.101105 -0.272598 -0.693955       NaN

In [18]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.603620  1.045708 -0.546797
1       NaN  0.947378 -0.331644  0.135510
2       NaN -0.449009  0.939663 -0.077299
3       NaN -1.198898  2.134181  1.051128
4 -0.583932 -0.556500 -1.161798       NaN
5 -0.806674  2.118057  1.022473       NaN
6 -2.101105 -0.272598 -0.693955       NaN

In [19]:
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'