In [1]:
import numpy as np

In [3]:
arr = np.arange(11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [7]:
A = np.random.randn(10)

In [8]:
A

array([-0.68736462,  0.74962712,  0.97320955, -1.37605254,  0.1062977 ,
       -0.73341979, -0.88873277,  0.61952697,  0.31663815, -0.17702469])

In [12]:
Z = np.random.randn(10)

In [13]:
Z

array([-0.33962185,  1.32977132, -1.61870902,  2.38106487, -0.67477458,
       -0.43349852,  0.44509551,  0.15982951,  1.49211039, -0.13021366])

In [14]:
# Binary Functions
np.add(A,Z)

array([-1.02698646,  2.07939845, -0.64549947,  1.00501234, -0.56847688,
       -1.16691831, -0.44363726,  0.77935648,  1.80874854, -0.30723836])

In [16]:
np.maximum(A,Z)

array([-0.33962185,  1.32977132,  0.97320955,  2.38106487,  0.1062977 ,
       -0.43349852,  0.44509551,  0.61952697,  1.49211039, -0.13021366])

In [19]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True