In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0]

0

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:3] = 100

In [8]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [9]:
slice_arr = arr[2:5]

In [10]:
slice_arr

array([100,   3,   4])

In [11]:
slice_arr[:]=55

In [12]:
arr

array([100, 100,  55,  55,  55,   5,   6,   7,   8,   9,  10])

In [13]:
arr_copy = arr.copy()

In [14]:
arr_copy

array([100, 100,  55,  55,  55,   5,   6,   7,   8,   9,  10])

In [17]:
arr_2d = np.array(([5,10,15],[20,25,25],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 25],
       [35, 40, 45]])

In [19]:
arr_2d[0][1]

10

In [20]:
arr_2d[:2][1:]

array([[20, 25, 25]])

In [21]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 25],
       [35, 40, 45]])

In [22]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 25]])

In [25]:
arr_2d2 = np.zeros((10,10))

In [26]:
arr_2d2

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [28]:
arr_length = arr_2d2.shape[1]

In [29]:
arr_length

10

In [30]:
for i in range(arr_length):
    arr_2d2[i] = i

In [31]:
arr_2d2

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])