In [5]:
import numpy as np

In [8]:
my_list1 = [1,2,3,4]

In [10]:
my_array1=np.array(my_list1)

In [11]:
my_array1

array([1, 2, 3, 4])

In [12]:
my_list2=[11,22,33,44]

In [13]:
my_list=[my_list1,my_list2]

In [14]:
my_array2=np.array(my_list)

In [15]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [16]:
my_array2.shape

(2, 4)

In [17]:
my_array2.dtype

dtype('int64')

In [18]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [19]:
my_zeros_array=np.zeros(5)

In [21]:
my_zeros_array.dtype

dtype('float64')

In [22]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [23]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])